### ISSUE TITLE
Spread operator causes error: Unexpected token ...

### ISSUE THREAD

**Issue by stkrzysiak** [jacobp100/js-code-stats#1]
Hi, 
I receive this error :
`Critical error
{ [SyntaxError: Unexpected token ...] index....`

I've narrowed it down to a file in my project that resembles this:
`export default ({ stylesObject }) => {
  return(<div  style={{ ...stylesObject}}>
    </div>);
}`

Once I remove the spread operator it works just fine.  I'll try to dig in on this later, unless someone knows a quick fix?

**Comment by stkrzysiak** [comment]
yeah, i reckon this just needs to be setup, https://www.npmjs.com/package/babel-plugin-transform-es2015-spread

If I get it working tonight I'll submit a PR.

**Comment by jacobp100** [comment]
Use `parser: 'babel-eslint’` in the options. Although feel free to reopen if you have further issues!
